quarkus.tls.key-store.p12.path=certs/archive.p12
quarkus.tls.key-store.p12.password=password
quarkus.http.insecure-requests=disabled

quarkus.tls.key-exchange-groups=X25519MLKEM768
quarkus.tls.pqc-enforcement-policy=strict
quarkus.tls.ssl-engine=openssl

quarkus.openshift.route.expose=true
# Passthrough forwards encrypted HTTPS traffic directly to the Quarkus container
quarkus.openshift.route.tls.termination=passthrough
quarkus.openshift.route.tls.insecure-edge-termination-policy=None

quarkus.openshift.base-jvm-image=registry.access.redhat.com/ubi10/openjdk-25:latest
