quarkus.tls.key-store.p12.path=certs/archive.p12
quarkus.tls.key-store.p12.password=password
quarkus.http.insecure-requests=disabled

quarkus.tls.key-exchange-groups=X25519MLKEM768
quarkus.tls.pqc-enforcement-policy=strict
quarkus.tls.ssl-engine=openssl
