quarkus.kubernetes.deploy=true
quarkus.kubernetes-client.namespace=ts-imupcjxjws
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deployment-target=openshift

quarkus.openshift.secret-volumes.app-keycloak-truststore-p12.secret-name=app-keycloak-truststore-p12
quarkus.openshift.secret-volumes.app-keycloak-truststore-p12.items."keycloak-truststore.p12".path=keycloak-truststore.p12
quarkus.openshift.mounts.app-keycloak-truststore-p12.name=app-keycloak-truststore-p12
quarkus.openshift.mounts.app-keycloak-truststore-p12.path=/certs

# uncomment to fix the issue
#quarkus.openshift.secret-volumes.app-keycloak-truststore-p12.items."keycloak-truststore.p12".mode=0444